### PR TITLE
Adding the Avatar Image Url as one of the available identity properti…

### PR DESCRIPTION
**Pull request by bmadaras**
…es to format via the IdentityFormatter.

### CODE REVIEW

**Comment by smpete** [comment]
What is the purpose of this change? Is it solely to override the default avatar should the `Identity` have no avatar URL? If so, the better way to do this might be to add that fallback to the `AvatarView` itself. This can even be set via a style should the default avatar be a local image, which I would assume is nearly always the case.

**Comment by bmadaras** [comment]
I could think of a few different ways that this would be useful.
One is the scenario that you describe but also giving the developer the option to default to a remote url if that is their desire.

Two is modifying the current url to add any sizing information to the request which the developers service would use to downsize the image if the device that the app is running on has a lower resolution to save bandwidth.

Third is the reason that I use this which is that we do not synchronise all of our users data to layer, we already have the users data as well as headshot url in the local database so once layer gives us the id of the user we delegate out to our user management logic to look up their information locally and then populate it when requests are made to the IdentityFormatter.  This made more sense to us since chat is one of the many modules we support in the app.

This seemed to be the most reasonable location to add it since just about all other displayable Identity data can be loaded/formatted via the IdentityFormatter.

**Comment by smpete** [comment]
In regards to the first use case (IE default local or remote URL), this should probably be done by adding default resource ID or URLs to the `AvatarView`. The reasoning for this is it would be impossible to use a resource ID with the way `AvatarView` is currently written. We'd want to keep the same flow for using a default image, whether it's remote or not.

The second use case is probably the most compelling reasons for moving this to the `IdentityFormatter`. However, let's focus on your use case. This is not the correct way to solve this issue. The avatar URL accessor is expected to be synchronous in all places that it's used in `AvatarView`. You should not be making potential disk reads for the URL.

**Comment by bmadaras** [comment]
In my case I am using Realm as the persistence layer so the access to the data has been made synchronously without performance issues, I have been using the changes from this pull request in our application.  The other option for myself or others is to cache the information.

But going back to the change, how is the addition of the url accessor any different from the display name or any other of the accessors in respect to it needing to be synchronous. The user of the library can shoot themselves in the foot by making a slow synchronous call for any of the accessors causing jank.

**Comment by smpete** [comment]
Sorry for the delay on this. We're discussing internally the best path forward. There might be more comprehensive changes to `AvatarView` and those would incorporate this functionality. Thus we might not want to introduce an intermediary API. I'll let you know what we decide.

Thanks!

**Comment by smpete** [comment]
After discussing with the team, we're going to keep this functionality out of the `IdentityFormatter`. The recommended path for the avatar URL source is via Layer `Identity`s that are synced via our server API. We do plan on improving `AvatarView` to allow for custom `AvatarView`s to be used to customize the functionality, including intercepting the URL fetch to add custom size parameters or to fetch the image from another location. We have this work item filed internally as `AND-1523` and will be in a future release. 

No major changes are on the horizon for `IdentityFormatter` or `AvatarView` so it shouldn't be too difficult to keep a custom fork up-to-date until we can improve the `AvatarView`.

**Pull request closed without merging**
